# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='address',
            field=models.CharField(default='', max_length=35),
            preserve_default=False,
        ),
    ]
