# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
