# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='totalReceived',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
